name: Check Stock Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # 每 5 分鐘執行一次
  workflow_dispatch:       # 也允許手動觸發

jobs:
  check-stock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stock checker
        run: python check_stock.py
